server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-SERVICE # lb 为负载均衡
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2022-12-23T14:17:02.116+08:00[Asia/Shanghai]
            - Cookie=username,zyy
        # 上面表示 如果要访问http://localhost:8001/get/payment/** 需要
        # http://localhost:9527/get/payment/**

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/get/lb/**   #断言,路径相匹配的进行路由
      discovery:
        locator:
          enabled: true
eureka:
  client:
    # 表示自己不是服务中心,需要检索服务
    fetch-registry: true
    # 需要将网关自己注册进Eureka注册中心
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
