server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka
spring:
  application:
    name: cloud-provider-hystrix-payment